/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prinfo;

/**
 *
 * @author Sarah-Marie JULES
 */
public class Suggestion extends javax.swing.JPanel {
    /**
     * Creates new form Suggestion
     * @param frame
     */
    public Suggestion(FenetrePrincipale frame) {
        initComponents();
        jCheckBox1.setVisible(frame.getestCo());
        jCheckBox2.setVisible(frame.getestCo());
        jCheckBox3.setVisible(frame.getestCo());
        jCheckBox4.setVisible(frame.getestCo());
        jCheckBox5.setVisible(frame.getestCo());
        jCheckBox6.setVisible(frame.getestCo());
        jCheckBox8.setVisible(frame.getestCo());
        jCheckBox9.setVisible(frame.getestCo());
        jCheckBox7.setVisible(frame.getestCo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleSuggestion = new javax.swing.JLabel();
        firstCategory = new javax.swing.JLabel();
        secondCategory = new javax.swing.JLabel();
        comicSugg11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        photoComic11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        comicSugg12 = new javax.swing.JPanel();
        title13 = new javax.swing.JLabel();
        photo13 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        comicSugg13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        photoComic12 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        comicSugg21 = new javax.swing.JPanel();
        photo21 = new javax.swing.JLabel();
        title21 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        comicSugg31 = new javax.swing.JPanel();
        title31 = new javax.swing.JLabel();
        photo31 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        comicSugg22 = new javax.swing.JPanel();
        title22 = new javax.swing.JLabel();
        photo22 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        comicSugg23 = new javax.swing.JPanel();
        title23 = new javax.swing.JLabel();
        photo23 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        comicSugg32 = new javax.swing.JPanel();
        title32 = new javax.swing.JLabel();
        photo32 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        comicSugg33 = new javax.swing.JPanel();
        title33 = new javax.swing.JLabel();
        photo33 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        thirdCategory = new javax.swing.JLabel();

        TitleSuggestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TitleSuggestion.setText("Suggestions");

        firstCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstCategory.setText("Catégorie1");

        secondCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondCategory.setText("Catégorie2");

        comicSugg11.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("title11");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photoComic11.setText("photo");
        photoComic11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox1.setText("Ajouter");

        javax.swing.GroupLayout comicSugg11Layout = new javax.swing.GroupLayout(comicSugg11);
        comicSugg11.setLayout(comicSugg11Layout);
        comicSugg11Layout.setHorizontalGroup(
            comicSugg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoComic11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comicSugg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comicSugg11Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jCheckBox1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        comicSugg11Layout.setVerticalGroup(
            comicSugg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg11Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(photoComic11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comicSugg12.setBackground(new java.awt.Color(255, 255, 102));

        title13.setText("titlle13");
        title13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photo13.setText("photo");
        photo13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox9.setText("Ajouter");

        javax.swing.GroupLayout comicSugg12Layout = new javax.swing.GroupLayout(comicSugg12);
        comicSugg12.setLayout(comicSugg12Layout);
        comicSugg12Layout.setHorizontalGroup(
            comicSugg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comicSugg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comicSugg12Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBox9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        comicSugg12Layout.setVerticalGroup(
            comicSugg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg12Layout.createSequentialGroup()
                        .addComponent(title13)
                        .addGap(29, 29, 29)
                        .addComponent(jCheckBox9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(photo13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comicSugg13.setBackground(new java.awt.Color(255, 255, 102));

        jLabel4.setText("titlle12");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photoComic12.setText("photo");
        photoComic12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox2.setText("Ajouter");

        javax.swing.GroupLayout comicSugg13Layout = new javax.swing.GroupLayout(comicSugg13);
        comicSugg13.setLayout(comicSugg13Layout);
        comicSugg13Layout.setHorizontalGroup(
            comicSugg13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoComic12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comicSugg13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg13Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg13Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(26, 26, 26))))
        );
        comicSugg13Layout.setVerticalGroup(
            comicSugg13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg13Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox2)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(photoComic12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comicSugg21.setBackground(new java.awt.Color(255, 255, 102));

        photo21.setText("photo");
        photo21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        title21.setText("titlle");
        title21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox3.setText("Ajouter");

        javax.swing.GroupLayout comicSugg21Layout = new javax.swing.GroupLayout(comicSugg21);
        comicSugg21.setLayout(comicSugg21Layout);
        comicSugg21Layout.setHorizontalGroup(
            comicSugg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comicSugg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg21Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comicSugg21Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jCheckBox3)))
                .addContainerGap())
        );
        comicSugg21Layout.setVerticalGroup(
            comicSugg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photo21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(comicSugg21Layout.createSequentialGroup()
                        .addComponent(title21)
                        .addGap(30, 30, 30)
                        .addComponent(jCheckBox3)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );

        comicSugg31.setBackground(new java.awt.Color(255, 255, 102));

        title31.setText("titlle");
        title31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photo31.setText("photo");
        photo31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox4.setText("Ajouter");

        javax.swing.GroupLayout comicSugg31Layout = new javax.swing.GroupLayout(comicSugg31);
        comicSugg31.setLayout(comicSugg31Layout);
        comicSugg31Layout.setHorizontalGroup(
            comicSugg31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo31, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comicSugg31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg31Layout.createSequentialGroup()
                        .addComponent(title31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(comicSugg31Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jCheckBox4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        comicSugg31Layout.setVerticalGroup(
            comicSugg31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photo31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(comicSugg31Layout.createSequentialGroup()
                        .addComponent(title31)
                        .addGap(30, 30, 30)
                        .addComponent(jCheckBox4)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );

        comicSugg22.setBackground(new java.awt.Color(255, 255, 102));

        title22.setText("titlle12");
        title22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photo22.setText("photo");
        photo22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox5.setText("Ajouter");

        javax.swing.GroupLayout comicSugg22Layout = new javax.swing.GroupLayout(comicSugg22);
        comicSugg22.setLayout(comicSugg22Layout);
        comicSugg22Layout.setHorizontalGroup(
            comicSugg22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo22, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comicSugg22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg22Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(comicSugg22Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jCheckBox5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        comicSugg22Layout.setVerticalGroup(
            comicSugg22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg22Layout.createSequentialGroup()
                        .addComponent(title22)
                        .addGap(29, 29, 29)
                        .addComponent(jCheckBox5)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(photo22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comicSugg23.setBackground(new java.awt.Color(255, 255, 102));

        title23.setText("titlle12");
        title23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photo23.setText("photo");
        photo23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox8.setText("Ajouter");

        javax.swing.GroupLayout comicSugg23Layout = new javax.swing.GroupLayout(comicSugg23);
        comicSugg23.setLayout(comicSugg23Layout);
        comicSugg23Layout.setHorizontalGroup(
            comicSugg23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo23, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comicSugg23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg23Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(comicSugg23Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jCheckBox8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        comicSugg23Layout.setVerticalGroup(
            comicSugg23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg23Layout.createSequentialGroup()
                        .addComponent(title23)
                        .addGap(29, 29, 29)
                        .addComponent(jCheckBox8)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(photo23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comicSugg32.setBackground(new java.awt.Color(255, 255, 102));

        title32.setText("tittle");
        title32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photo32.setText("photo");
        photo32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox6.setText("Ajouter");

        javax.swing.GroupLayout comicSugg32Layout = new javax.swing.GroupLayout(comicSugg32);
        comicSugg32.setLayout(comicSugg32Layout);
        comicSugg32Layout.setHorizontalGroup(
            comicSugg32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo32, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comicSugg32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg32Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(comicSugg32Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jCheckBox6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        comicSugg32Layout.setVerticalGroup(
            comicSugg32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg32Layout.createSequentialGroup()
                        .addComponent(title32)
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBox6)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(photo32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comicSugg33.setBackground(new java.awt.Color(255, 255, 102));

        title33.setText("tittle");
        title33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photo33.setText("photo");
        photo33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox7.setText("Ajouter");

        javax.swing.GroupLayout comicSugg33Layout = new javax.swing.GroupLayout(comicSugg33);
        comicSugg33.setLayout(comicSugg33Layout);
        comicSugg33Layout.setHorizontalGroup(
            comicSugg33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comicSugg33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo33, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comicSugg33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg33Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title33, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comicSugg33Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBox7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        comicSugg33Layout.setVerticalGroup(
            comicSugg33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicSugg33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicSugg33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicSugg33Layout.createSequentialGroup()
                        .addComponent(title33)
                        .addGap(30, 30, 30)
                        .addComponent(jCheckBox7)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(photo33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        thirdCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thirdCategory.setText("Catégorie3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thirdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(firstCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TitleSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comicSugg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comicSugg31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comicSugg11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comicSugg32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comicSugg22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comicSugg13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(65, 65, 65)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comicSugg23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comicSugg33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comicSugg12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(16, 16, 16)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comicSugg12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comicSugg13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comicSugg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(secondCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comicSugg21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comicSugg22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comicSugg23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(thirdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comicSugg31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comicSugg33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comicSugg32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleSuggestion;
    private javax.swing.JPanel comicSugg11;
    private javax.swing.JPanel comicSugg12;
    private javax.swing.JPanel comicSugg13;
    private javax.swing.JPanel comicSugg21;
    private javax.swing.JPanel comicSugg22;
    private javax.swing.JPanel comicSugg23;
    private javax.swing.JPanel comicSugg31;
    private javax.swing.JPanel comicSugg32;
    private javax.swing.JPanel comicSugg33;
    private javax.swing.JLabel firstCategory;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel photo13;
    private javax.swing.JLabel photo21;
    private javax.swing.JLabel photo22;
    private javax.swing.JLabel photo23;
    private javax.swing.JLabel photo31;
    private javax.swing.JLabel photo32;
    private javax.swing.JLabel photo33;
    private javax.swing.JLabel photoComic11;
    private javax.swing.JLabel photoComic12;
    private javax.swing.JLabel secondCategory;
    private javax.swing.JLabel thirdCategory;
    private javax.swing.JLabel title13;
    private javax.swing.JLabel title21;
    private javax.swing.JLabel title22;
    private javax.swing.JLabel title23;
    private javax.swing.JLabel title31;
    private javax.swing.JLabel title32;
    private javax.swing.JLabel title33;
    // End of variables declaration//GEN-END:variables
}
