/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AffichageCollection;

import Collec.Comic_Collec;
import User.User;
import Collec.User_serie;
import java.awt.GridLayout;
import java.util.HashSet;
import java.util.Iterator;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
/**
 *
 * @author Alexi
 */
public class UserSeriePanel extends javax.swing.JPanel {
    private User user;
    private User_serie serie;
    private HashSet<ComicPanelCollection> comic_panels; 
    /**
     * Creates new form UserSeriePanel
     */
    public UserSeriePanel(User user,User_serie serie) {
        initComponents();
        this.user=user;
        this.serie=serie;
        this.comic_panels= new HashSet<>();
        InitUserSeriePanelCollection();
    }
    
    public void InitUserSeriePanelCollection(){
        nomSerie.setText(serie.getName());
        contentpageserie.setLayout(new GridLayout(1,6));
        
        
        for (Comic_Collec comic : serie.getUserSerie()) {//MOdifier pour avoir la serie possédée
            comic_panels.add(new ComicPanelCollection(this.user,comic));
        }
        Iterator<ComicPanelCollection> iterator = comic_panels.iterator();
        
        for (int i = 0; i < 6; i++) {
            if (iterator.hasNext()) {
                contentpageserie.add(iterator.next());
            }      
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afficherGauche = new javax.swing.JButton();
        afficherDroite = new javax.swing.JButton();
        nomSerie = new javax.swing.JLabel();
        contentpageserie = new javax.swing.JPanel();

        setBackground(new Color(99, 99, 99));
        setMaximumSize(new java.awt.Dimension(1030, 32767));
        setPreferredSize(new Dimension(977, 253));

        afficherGauche.setBackground(new java.awt.Color(153, 153, 153));
        afficherGauche.setForeground(new Color(0, 0, 0));
        afficherGauche.setText("<");
        afficherGauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherGaucheActionPerformed(evt);
            }
        });

        afficherDroite.setBackground(new java.awt.Color(153, 153, 153));
        afficherDroite.setForeground(new Color(0, 0, 0));
        afficherDroite.setText(">");
        afficherDroite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherDroiteActionPerformed(evt);
            }
        });

        nomSerie.setBackground(new Color(99, 99, 99));
        nomSerie.setForeground(new java.awt.Color(255, 255, 255));
        nomSerie.setText("NomSerie");

        contentpageserie.setBackground(new Color(99, 99, 99));

        javax.swing.GroupLayout contentpageserieLayout = new javax.swing.GroupLayout(contentpageserie);
        contentpageserie.setLayout(contentpageserieLayout);
        contentpageserieLayout.setHorizontalGroup(
            contentpageserieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        contentpageserieLayout.setVerticalGroup(
            contentpageserieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(afficherGauche)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(contentpageserie, GroupLayout.PREFERRED_SIZE, 884, GroupLayout.PREFERRED_SIZE)
        					.addGap(6)
        					.addComponent(afficherDroite))
        				.addComponent(nomSerie, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addComponent(nomSerie, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(afficherDroite, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        				.addComponent(afficherGauche, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        				.addComponent(contentpageserie, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        			.addGap(22))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void afficherGaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherGaucheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afficherGaucheActionPerformed

    private void afficherDroiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherDroiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afficherDroiteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afficherDroite;
    private javax.swing.JButton afficherGauche;
    private javax.swing.JPanel contentpageserie;
    private javax.swing.JLabel nomSerie;
    // End of variables declaration//GEN-END:variables
}
