/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Suggestion;

import API.Comic;
import API.api_connection;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.List;
import prinfo.FenetrePrincipale;

/**
 *
 * @author Sarah-Marie JULES
 */
public class Suggestion extends javax.swing.JPanel {
    private api_connection test;
    /**
     * Creates new form Suggestion
     * @param frame
     * @throws java.io.IOException
     */
    public Suggestion(FenetrePrincipale frame) throws IOException {
        test = new api_connection();
        initComponents();
        this.suggestion(frame);
        
    }
    
    public void suggestion(FenetrePrincipale frame) throws IOException{
        contentSuggestion.setLayout(new GridLayout(3,1));
        List<Comic> firstCategorie = test.getLastComics();
        contentSuggestion.add(new Categorie(frame,firstCategorie.subList(0,3),"Derniers Ajouts"));
        List<Comic> secondCategorie = test.getRandomComics();
        if (frame.getestCo()){
        } else {
            contentSuggestion.add(new Categorie(frame,secondCategorie.subList(0,3),"Aléatoires"));
        }
        
        contentSuggestion.setVisible(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleSuggestion = new javax.swing.JLabel();
        contentSuggestion = new javax.swing.JPanel();

        setBackground(new java.awt.Color(55, 55, 55));

        TitleSuggestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TitleSuggestion.setForeground(new java.awt.Color(255, 255, 255));
        TitleSuggestion.setText("Suggestions");

        contentSuggestion.setBackground(new java.awt.Color(55, 55, 55));

        javax.swing.GroupLayout contentSuggestionLayout = new javax.swing.GroupLayout(contentSuggestion);
        contentSuggestion.setLayout(contentSuggestionLayout);
        contentSuggestionLayout.setHorizontalGroup(
            contentSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentSuggestionLayout.setVerticalGroup(
            contentSuggestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(473, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentSuggestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentSuggestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleSuggestion;
    private javax.swing.JPanel contentSuggestion;
    // End of variables declaration//GEN-END:variables
}
